const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: ()    => ipcRenderer.send('window-minimize'),
  close:    ()    => ipcRenderer.send('window-close'),

  getConfig:             () => ipcRenderer.invoke('get-config'),
  getMediaFiles:         () => ipcRenderer.invoke('get-media-files'),
  getDefaultInstallPath: () => ipcRenderer.invoke('get-default-install-path'),
  selectInstallPath:     () => ipcRenderer.invoke('select-install-path'),
  openSteamConsole:      () => ipcRenderer.invoke('open-steam-console'),
  checkDepots:           () => ipcRenderer.invoke('check-depots'),
  installGame:           (p) => ipcRenderer.invoke('install-game', p),
  verifyFiles:           (p) => ipcRenderer.invoke('verify-files', p),
  launchGame:            (p) => ipcRenderer.invoke('launch-game', p),
  checkInstall:          () => ipcRenderer.invoke('check-install'),
  runAutoPaste:          () => ipcRenderer.invoke('run-auto-paste'),
  applyGithubUpdate:     (d) => ipcRenderer.invoke('apply-github-update', d),
  openExternal:          (u) => ipcRenderer.invoke('open-external', u),
  checkDiskSpace:        (p) => ipcRenderer.invoke('check-disk-space', p),
  applyLauncherUpdate:   (d) => ipcRenderer.invoke('apply-launcher-update', d),
  openFolder:            (p) => ipcRenderer.invoke('open-folder', p),
  checkUpdate:           ()  => ipcRenderer.invoke('check-update'),
  createShortcut:        (p) => ipcRenderer.invoke('create-shortcut', p),
  watchDepotProgress:    ()  => ipcRenderer.invoke('watch-depot-progress'),
  stopDepotWatch:        ()  => ipcRenderer.invoke('stop-depot-watch'),
  getAudioFiles:         ()  => ipcRenderer.invoke('get-audio-files'),
  queryServers:          ()  => ipcRenderer.invoke('query-servers'),
  connectServer:         (d) => ipcRenderer.invoke('connect-server', d),

  onConfig:                    (cb) => ipcRenderer.on('config',                    (_e,d) => cb(d)),
  onAlreadyInstalled:          (cb) => ipcRenderer.on('already-installed',          (_e,d) => cb(d)),
  onInstallProgress:           (cb) => ipcRenderer.on('install-progress',           (_e,d) => cb(d)),
  onVerifyProgress:            (cb) => ipcRenderer.on('verify-progress',            (_e,d) => cb(d)),
  onAutoPasteStatus:           (cb) => ipcRenderer.on('auto-paste-status',          (_e,d) => cb(d)),
  onUpdateAvailable:           (cb) => ipcRenderer.on('update-available',           (_e,d) => cb(d)),
  onUpdateProgress:            (cb) => ipcRenderer.on('update-progress',            (_e,d) => cb(d)),
  onLauncherUpdateAvailable:   (cb) => ipcRenderer.on('launcher-update-available',  (_e,d) => cb(d)),
  onLauncherUpdateProgress:    (cb) => ipcRenderer.on('launcher-update-progress',   (_e,d) => cb(d)),
  onDepotDownloadProgress:     (cb) => ipcRenderer.on('depot-download-progress',    (_e,d) => cb(d)),
});
