const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  minimize: ()    => ipcRenderer.send('window-minimize'),
  close:    ()    => ipcRenderer.send('window-close'),
  quit:     ()    => ipcRenderer.send('window-quit'),

  getConfig:             () => ipcRenderer.invoke('get-config'),
  getLauncherState:      () => ipcRenderer.invoke('get-launcher-state'),
  updateLauncherState:   (d) => ipcRenderer.invoke('update-launcher-state', d),
  getMediaFiles:         () => ipcRenderer.invoke('get-media-files'),
  getDefaultInstallPath: () => ipcRenderer.invoke('get-default-install-path'),
  selectInstallPath:     () => ipcRenderer.invoke('select-install-path'),
  openSteamConsole:      () => ipcRenderer.invoke('open-steam-console'),
  checkDepots:           () => ipcRenderer.invoke('check-depots'),
  installGame:           (p) => ipcRenderer.invoke('install-game', p),
  verifyFiles:           (p) => ipcRenderer.invoke('verify-files', p),
  launchGame:            (p) => ipcRenderer.invoke('launch-game', p),
  checkInstall:          () => ipcRenderer.invoke('check-install'),
  openExternal:          (u) => ipcRenderer.invoke('open-external', u),
  checkDiskSpace:        (p) => ipcRenderer.invoke('check-disk-space', p),
  openFolder:            (p) => ipcRenderer.invoke('open-folder', p),
  checkUpdate:           ()  => ipcRenderer.invoke('check-update'),
  createShortcut:        (p) => ipcRenderer.invoke('create-shortcut', p),
  watchDepotProgress:    ()  => ipcRenderer.invoke('watch-depot-progress'),
  stopDepotWatch:        ()  => ipcRenderer.invoke('stop-depot-watch'),
  getAudioFiles:         ()  => ipcRenderer.invoke('get-audio-files'),
  getVideoFiles:         ()  => ipcRenderer.invoke('get-video-files'),
  queryServers:          ()  => ipcRenderer.invoke('query-servers'),
  connectServer:         (d) => ipcRenderer.invoke('connect-server', d),
  queryServerIp:         (d) => ipcRenderer.invoke('query-server-ip', d),
  openSteamDepots:       ()  => ipcRenderer.invoke('open-steam-depots'),
  restartForUpdate:      ()  => ipcRenderer.invoke('restart-for-update'),
  verifyGameFiles:       (p) => ipcRenderer.invoke('verify-game-files', p),

  onConfig:                    (cb) => ipcRenderer.on('config',                    (_e,d) => cb(d)),
  onAlreadyInstalled:          (cb) => ipcRenderer.on('already-installed',          (_e,d) => cb(d)),
  onInstallProgress:           (cb) => ipcRenderer.on('install-progress',           (_e,d) => cb(d)),
  onVerifyProgress:            (cb) => ipcRenderer.on('verify-progress',            (_e,d) => cb(d)),
  onUpdateStatus:              (cb) => ipcRenderer.on('update-status',              (_e,d) => cb(d)),
  onDepotDownloadProgress:     (cb) => ipcRenderer.on('depot-download-progress',    (_e,d) => cb(d)),
  onGameExited:                (cb) => ipcRenderer.on('game-exited',                (_e,d) => cb(d)),
  onUpdateReady:               (cb) => ipcRenderer.on('update-ready',               (_e,d) => cb(d)),
  onUpdateDownloadProgress:    (cb) => ipcRenderer.on('update-download-progress',    (_e,d) => cb(d)),
  onLauncherFeed:              (cb) => ipcRenderer.on('launcher-feed',              (_e,d) => cb(d)),
  onNews:                      (cb) => ipcRenderer.on('news',                        (_e,d) => cb(d)),
  onMusicLibraryUpdated:       (cb) => ipcRenderer.on('music-library-updated',      (_e,d) => cb(d)),
  onMusicSyncError:            (cb) => ipcRenderer.on('music-sync-error',           (_e,d) => cb(d)),
  onVideoLibraryUpdated:       (cb) => ipcRenderer.on('video-library-updated',      (_e,d) => cb(d)),
  onVideoSyncError:            (cb) => ipcRenderer.on('video-sync-error',           (_e,d) => cb(d)),
});
